apiVersion: v1
kind: ReplicationController
metadata:
  name: vaultweb
  labels:
    name: vaultweb
spec:
  replicas: 1
  selector:
    name: vaultweb
  template:
    metadata:
      labels:
        name: vaultweb
    spec:
      containers:
      - name: vaultweb
        image: quay.io/ukhomeofficedigital/vaultweb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: VAULT_SERVER
            value: $VAULT_URL
          - name: VAULT_TOKEN
            value: $TOKEN
