apiVersion: v1
kind: Service
metadata:
  name: vaultweb-service
  labels:
    name: vaultweb-service
    visibility: internal
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 5000
  selector:
    name: vaultweb
