apiVersion: v1
kind: Service
metadata:
  name: vaultweb_service
  labels:
    name: vaultweb_service
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 5000
  selector:
    name: vaultweb
